### PR TITLE
Fixed my issue with batch processing

### PR DESCRIPTION
**Pull request by yooper**

### CODE REVIEW

**Comment by kachkaev** [comment]
Hi @yooper,

Thanks for the PR! Which OS are you using? 

I don't quite remember why there wasn't that extra line for pipes[1] initially. It could be that it made things in OSX worse. According to you knowledge, may your change cause any problems in any OS?

I'll be happy to merge the PR, just want to make sure the fix is cross-platform. I don't have an opportunity to test the library well.

**Comment by yooper** [comment]
I do not have a OSX system to test on and according to the documentation, http://php.net/manual/en/function.stream-set-blocking.php#110997 , set_stream_blocking does not work on windows in when the pipe is opened by proc_open. Do you have an OSX system?

**Comment by kachkaev** [comment]
Yep.

**Comment by yooper** [comment]
I am closing this PR. I opted to use R's existing batch functionality.

**Pull request closed without merging**
